### ISSUE TITLE
FH Guide

### ISSUE THREAD

**Issue by BTBlueTiger** [Lulon27/projektmanagement#1]
# FH Guide

Was stört mich und was ist irgendwie total diffus... meine Organisation, die Organisation, alle Organisation

### Idee an sich 
Alles was man sich erfragen muss, oder ständig neu sucht oder sich immer fragt, aber man doch wieder zu faul war, zu suchen oder zu sammeln.
Beispiele die mir einfielen:
## Modulspezifisch
- Konkrete Sammelstelle für modulspezifische Dinge, beispielsweise Diagramme oder Schablonen
- Sammelstelle für etwaige Aufzeichnungen, Karteikarten etc.
- Bewertung für Workload (anonymisiert)
- Kriterien und Bewertung für bestimmte Anforderungen, Beispiel:
    - Mathematik Stufe 10
    - Logik Stufe 5 
    - Java Stufe 2
- Beispiele zu: So macht mans, so kannste es auch gleich lassen 
## Schnittstellen zu bekannten Diensten
- Discord
- Zoom
- WhatsApp
- GitLab / GitHub
_Oft such ich immer das Gleiche ..._
## FAQ Like Forum/Antwort allerlei:
- Brauch ich alle ETC Punkte? 
- Was wenn ich das dritte Mal durchgefallen bin, wo jetzt weiterstudieren?
- Sollte ich schon Module aus anderen Semestern anfangen 
_Generell Fragen, die man sich als Neuling stellt oder die man sich noch nicht stellt aber ganz interessant sind, fragen können dann geschlossen und in eine Liste mit wichtig aufgenommen und auch wieder gelöscht werden_
## Liste von Wahlmodulen
- Hier eventuell ob aktiv inaktiv
- Bewertung von Aufwand
- Bewertung der Anforderungen
- Sinnvoll wenn ich ...., nicht sinnvoll, wenn ich dies und das ...
#### Endwort
Quasi, dass was WhatsApp und Discord darstellt, nur verknüpft mit diesen und ergänzt. Bonus für uns wir könnten quasi Module für dieses Semester mit lernen und gleichzeitig das Projekt bearbeiten

**Comment by BTBlueTiger** [comment]
[Project_Canvas_FH_Guide.pdf](https://github.com/Lulon27/projektmanagement/files/7473263/Project_Canvas_FH_Guide.pdf)

**Comment by BTBlueTiger** [comment]
[Project_Canvas_FH_Guide.pdf](https://github.com/Lulon27/projektmanagement/files/7473402/Project_Canvas_FH_Guide.pdf)

**Comment by BTBlueTiger** [comment]
Meine Grund Use Case Idee, sah so aus : 
![Use-Case-Diagram](https://user-images.githubusercontent.com/92604963/140894412-30c3ea3b-e8f5-4e2d-94dc-1b2bc775b40b.png)

Dieser kann, muss aber nicht verändert werden.

**Comment by Lulon27** [comment]
Was ist ein "Lecture"?

**Comment by Lulon27** [comment]
Ich hab ehrlich gesagt das Gefühl, dass es besser ist, wenn wir alle Diagramme, Dokumentationen, usw. außerhalb von Code auf deutsch machen. Code selber, Code-Dokumentation, Commit-Messages natürlich auf englisch.

**Comment by BTBlueTiger** [comment]
Können wir so machen.

Und bei dem Lecture, hab ich das "r" am Ende vergessen.
Lecturer natürlich.
